### ISSUE TITLE
Firefox-bug? ReferenceError: RotatingFileStream is not defined

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index-indexing-in-browser#1]
Get this error (and a couple of warnings) when I open the index.html in Firefox:

```
ReferenceError: RotatingFileStream is not defined
```

Works in Chrome, but fails in Firefox on OSX. I'm using the following version:

```
40.0.3
```

![screen shot 2015-09-21 at 15 30 07](https://cloud.githubusercontent.com/assets/236656/9993047/f4db4140-6075-11e5-8e0f-661bc76ba7ac.png)

**Comment by eklem** [comment]
![screen shot 2015-09-21 at 15 35 21](https://cloud.githubusercontent.com/assets/236656/9993109/41037ccc-6076-11e5-8dfb-1e3347d304a0.png)

**Comment by eklem** [comment]
Checked a little, and it seems this an error within `node-bunyan`, and it is fixed in a later version: https://github.com/trentm/node-bunyan/issues/223

**Comment by fergiemcdowall** [comment]
I wonder if bumping search-index up to 0.6.11 fixes this?

**Comment by eklem** [comment]
Think so. If I read right, it's fixed in bunyan v1.5.0. and v0.6.11 of search-index depend on v.1.5.1 of bunyan.

**Comment by eklem** [comment]
Will test!

**Comment by fergiemcdowall** [comment]
:+1:
